name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          path: build
      - uses: cypress-io/github-action@v2
        with:
          runTests: false
          build: npm run buiild
